#! /bin/sh

set -e

#DEBHELPER#

if [ "$1" = "purge" ]; then
	deluser --quiet --system whoopsie > /dev/null || true
	chmod g-s /var/crash >/dev/null 2>&1
	chgrp root /var/crash >/dev/null 2>&1
fi

exit 0
